In [1]:
# import libraries
import pandas as pd
import numpy as np 
import tensorflow as tf 
import tensorflow_decision_forests as tfdf

2024-02-03 15:13:23.324568: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-03 15:13:23.327301: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-03 15:13:23.391315: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-03 15:13:23.392639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-03 15:13:24.385774: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:root:TensorFlow Decision Forests 1.5.0 is compatible with the following TensorFlow Versions: ['2.13.0']. However, TensorFlow 2.13.1 was detected. This can cause issues with the TF API and symbols in the custom C++ ops. See the TF and TF-DF compatibility table at https://github.com/tensorflow/decision-forests/blob/main/documentation/known_issues.md#compatibility-table.

In [2]:
#load data 
data = pd.read_csv("Data/card_transdata.csv")

In [3]:
data

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

We have 1000000 records of data for use.

In [4]:
#renaming columns names for simplicity
data.rename(columns = {'distance_from_home':'dist_f_home','distance_from_last_transaction':'dist_f_last_trans'})

,dist_f_home,dist_f_last_trans,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

 Will use 80% for training,20% for testing. Will take 20 records out of testing for demonstation.

In [5]:
#shuffles the data
data_shuffled = data.sample(frac=1,random_state= 50)


#percent of data used as test split
split_percent = 0.8



#get the index to split the data
total_rows = data.shape[0]
train_size = int(total_rows*split_percent)

#train and test data
train = data_shuffled.iloc[:train_size]
test = data_shuffled.iloc[train_size:]

In [6]:
train

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
945737,0.491089,7.779744,2.121038,0.0,1.0,0.0,1.0,0.0
852739,0.126181,3.970530,1.552483,0.0,1.0,0.0,1.0,0.0
776155,1.869991,0.151482,1.804444,0.0,0.0,0.0,1.0,0.0
542223,13.290477,1.295650,0.389154,1.0,0.0,0.0,1.0,0.0
728363,128.621568,0.028654,0.910323,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
470002,22.015117,10.395801,0.581979,1.0,0.0,0.0,1.0,0.0
305214,4.429420,0.127778,1.032126,1.0,0.0,0.0,1.0,0.0
444993,3.171650,15.414614,1.433952,1.0,0.0,1.0,1.0,0.0
446608,20.480566,15.132238,1.494043,1.0,1.0,0.0,0.0,0.0
143221,50.126005,0.038396,2.896471,1.0,0.0,0.0,1.0,0.0

In [7]:
test

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
543158,1.880605,0.285949,0.532518,0.0,1.0,0.0,1.0,0.0
90869,10.957813,1.797360,15.665324,1.0,0.0,0.0,1.0,1.0
53752,13.064408,4.366115,0.283263,1.0,1.0,0.0,1.0,0.0
651163,3.638811,0.427399,0.729624,1.0,0.0,0.0,1.0,0.0
671781,1.659697,13.140005,0.833232,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
441633,9.214598,11.997814,0.752263,1.0,1.0,0.0,1.0,0.0
677997,165.847514,1.707527,0.238962,1.0,0.0,0.0,1.0,1.0
239499,6.203416,2.240537,0.240108,1.0,0.0,1.0,1.0,0.0
103904,1.440871,3.985760,0.131841,0.0,0.0,0.0,1.0,0.0
931504,34.956244,15.901582,0.230555,1.0,1.0,1.0,0.0,0.0

In [8]:
app_test = test.iloc[:20]
test.drop(test.index[:20],inplace=True)

/tmp/ipykernel_3934/4037853475.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop(test.index[:20],inplace=True)

In [9]:
app_test

app_test.to_csv('app_test_data.csv', index=False)

In [10]:
test

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
97201,12.377613,4.494125,1.303883,1.0,0.0,0.0,1.0,0.0
511078,7.497894,0.576066,3.157412,1.0,1.0,0.0,0.0,0.0
321639,76.707518,1.954241,0.269328,1.0,1.0,0.0,0.0,0.0
32496,22.921780,0.364255,1.972151,1.0,0.0,1.0,1.0,0.0
257629,0.784526,0.756796,0.488812,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
441633,9.214598,11.997814,0.752263,1.0,1.0,0.0,1.0,0.0
677997,165.847514,1.707527,0.238962,1.0,0.0,0.0,1.0,1.0
239499,6.203416,2.240537,0.240108,1.0,0.0,1.0,1.0,0.0
103904,1.440871,3.985760,0.131841,0.0,0.0,0.0,1.0,0.0
931504,34.956244,15.901582,0.230555,1.0,1.0,1.0,0.0,0.0

Data has been checked and "test" is the data that will be used for tesing, "train" for training, and "app_test" is the 20 records for the demonstration.

In [11]:
label ='fraud'
train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(train,label=label)
test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(test,label=label)

In [12]:
model = tfdf.keras.RandomForestModel()

Use /tmp/tmpbac8yd3k as temporary training directory

In [13]:
model.fit(train_ds)

Reading training dataset...
Training dataset read in 0:00:09.887847. Found 800000 examples.
Training model...
Model trained in 0:01:39.119784
Compiling model...

[INFO 24-02-03 15:15:43.7551 EST kernel.cc:1243] Loading model from path /tmp/tmpbac8yd3k/model/ with prefix 2e3df3900a904b63
[INFO 24-02-03 15:15:43.8023 EST decision_forest.cc:660] Model loaded with 300 root(s), 21366 node(s), and 7 input feature(s).
[INFO 24-02-03 15:15:43.8024 EST abstract_model.cc:1311] Engine "RandomForestOptPred" built
[INFO 24-02-03 15:15:43.8025 EST kernel.cc:1075] Use fast generic engine

WARNING:tensorflow:AutoGraph could not transform <function simple_ml_inference_op_with_handle at 0x7f76a5dd0160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING:tensorflow:AutoGraph could not transform <function simple_ml_inference_op_with_handle at 0x7f76a5dd0160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING: AutoGraph could not transform <function simple_ml_inference_op_with_handle at 0x7f76a5dd0160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model compiled.

In [17]:
model.compile(metrics=["accuracy"])
eval = model.evaluate(test_ds,return_dict =True)

for name, value in eval.items():
    print(f'{name}: {value:.4f}')

200/200 [==============================] - 2s 11ms/step - loss: 0.0000e+00 - accuracy: 1.0000
loss: 0.0000
accuracy: 1.0000

In [18]:
model.summary()

Model: "random_forest_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1 (1.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 1 (1.00 Byte)
_________________________________________________________________
Type: "RANDOM_FOREST"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (7):
	distance_from_home
	distance_from_last_transaction
	online_order
	ratio_to_median_purchase_price
	repeat_retailer
	used_chip
	used_pin_number

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1. "ratio_to_median_purchase_price"  0.555401 ################
    2.             "distance_from_home"  0.360389 #######
    3.                   "online_order"  0.325564 ######
    4. "distance_from_last_transaction"  0.220217 ##
    5.                "used_pin_number"  0.206756 #
    6.                      "used_chip"  0.200368 #
    7.                "repeat_retailer"  0.166811

Variable Importance: NUM_AS_ROOT:
    1. "ratio_to_median_purchase_price" 181.000000 ################
    2.             "distance_from_home" 83.000000 #######
    3.                   "online_order" 35.000000 ###
    4.                "used_pin_number"  1.000000

Variable Importance: NUM_NODES:
    1.                "used_pin_number" 2619.000000 ################
    2. "distance_from_last_transaction" 2228.000000 #############
    3.             "distance_from_home" 1749.000000 #########
    4.                      "used_chip" 1439.000000 #######
    5.                   "online_order" 1080.000000 ####
    6. "ratio_to_median_purchase_price" 1014.000000 ####
    7.                "repeat_retailer" 404.000000

Variable Importance: SUM_SCORE:
    1. "ratio_to_median_purchase_price" 32827042.117316 ################
    2.             "distance_from_home" 11247000.884838 #####
    3.                   "online_order" 10979026.997263 #####
    4.                "used_pin_number" 5967585.049132 ##
    5. "distance_from_last_transaction" 5614549.514796 ##
    6.                      "used_chip" 3889513.850655 #
    7.                "repeat_retailer" 609692.525764



Winner takes all: true
Out-of-bag evaluation: accuracy:0.999986 logloss:4.97547e-05
Number of trees: 300
Total number of nodes: 21366

Number of nodes by tree:
Count: 300 Average: 71.22 StdDev: 8.45488
Min: 53 Max: 113 Ignored: 0
----------------------------------------------
[  53,  56)  2   0.67%   0.67%
[  56,  59)  6   2.00%   2.67% #
[  59,  62) 21   7.00%   9.67% ###
[  62,  65) 25   8.33%  18.00% ####
[  65,  68) 64  21.33%  39.33% ##########
[  68,  71) 34  11.33%  50.67% #####
[  71,  74) 56  18.67%  69.33% #########
[  74,  77) 24   8.00%  77.33% ####
[  77,  80) 28   9.33%  86.67% ####
[  80,  83) 10   3.33%  90.00% ##
[  83,  86) 10   3.33%  93.33% ##
[  86,  89)  5   1.67%  95.00% #
[  89,  92)  9   3.00%  98.00% #
[  92,  95)  2   0.67%  98.67%
[  95,  98)  1   0.33%  99.00%
[  98, 101)  0   0.00%  99.00%
[ 101, 104)  1   0.33%  99.33%
[ 104, 107)  1   0.33%  99.67%
[ 107, 110)  0   0.00%  99.67%
[ 110, 113]  1   0.33% 100.00%

Depth by leafs:
Count: 10833 Average: 5.65291 StdDev: 1.20159
Min: 2 Max: 13 Ignored: 0
----------------------------------------------
[  2,  3)    1   0.01%   0.01%
[  3,  4)  412   3.80%   3.81% #
[  4,  5) 1195  11.03%  14.84% ###
[  5,  6) 3206  29.59%  44.44% #########
[  6,  7) 3655  33.74%  78.18% ##########
[  7,  8) 1898  17.52%  95.70% #####
[  8,  9)  304   2.81%  98.50% #
[  9, 10)  105   0.97%  99.47%
[ 10, 11)   39   0.36%  99.83%
[ 11, 12)   11   0.10%  99.94%
[ 12, 13)    5   0.05%  99.98%
[ 13, 13]    2   0.02% 100.00%

Number of training obs by leaf:
Count: 10833 Average: 22154.5 StdDev: 90415.6
Min: 5 Max: 672507 Ignored: 0
----------------------------------------------
[      5,  33630) 9975  92.08%  92.08% ##########
[  33630,  67255)  313   2.89%  94.97%
[  67255, 100880)   17   0.16%  95.13%
[ 100880, 134505)    2   0.02%  95.14%
[ 134505, 168130)   51   0.47%  95.62%
[ 168130, 201755)    1   0.01%  95.62%
[ 201755, 235381)   38   0.35%  95.98%
[ 235381, 269006)  143   1.32%  97.30%
[ 269006, 302631)   39   0.36%  97.66%
[ 302631, 336256)    3   0.03%  97.68%
[ 336256, 369881)    6   0.06%  97.74%
[ 369881, 403506)   18   0.17%  97.90%
[ 403506, 437131)   89   0.82%  98.73%
[ 437131, 470757)   14   0.13%  98.86%
[ 470757, 504382)    0   0.00%  98.86%
[ 504382, 538007)    4   0.04%  98.89%
[ 538007, 571632)    0   0.00%  98.89%
[ 571632, 605257)    5   0.05%  98.94%
[ 605257, 638882)    0   0.00%  98.94%
[ 638882, 672507]  115   1.06% 100.00%

Attribute in nodes:
	2619 : used_pin_number [NUMERICAL]
	2228 : distance_from_last_transaction [NUMERICAL]
	1749 : distance_from_home [NUMERICAL]
	1439 : used_chip [NUMERICAL]
	1080 : online_order [NUMERICAL]
	1014 : ratio_to_median_purchase_price [NUMERICAL]
	404 : repeat_retailer [NUMERICAL]

Attribute in nodes with depth <= 0:
	181 : ratio_to_median_purchase_price [NUMERICAL]
	83 : distance_from_home [NUMERICAL]
	35 : online_order [NUMERICAL]
	1 : used_pin_number [NUMERICAL]

Attribute in nodes with depth <= 1:
	284 : ratio_to_median_purchase_price [NUMERICAL]
	225 : distance_from_home [NUMERICAL]
	223 : online_order [NUMERICAL]
	66 : distance_from_last_transaction [NUMERICAL]
	64 : used_pin_number [NUMERICAL]
	33 : used_chip [NUMERICAL]
	5 : repeat_retailer [NUMERICAL]

Attribute in nodes with depth <= 2:
	505 : online_order [NUMERICAL]
	456 : distance_from_home [NUMERICAL]
	406 : ratio_to_median_purchase_price [NUMERICAL]
	251 : distance_from_last_transaction [NUMERICAL]
	233 : used_pin_number [NUMERICAL]
	161 : used_chip [NUMERICAL]
	87 : repeat_retailer [NUMERICAL]

Attribute in nodes with depth <= 3:
	825 : distance_from_home [NUMERICAL]
	756 : online_order [NUMERICAL]
	632 : used_pin_number [NUMERICAL]
	614 : distance_from_last_transaction [NUMERICAL]
	576 : ratio_to_median_purchase_price [NUMERICAL]
	510 : used_chip [NUMERICAL]
	172 : repeat_retailer [NUMERICAL]

Attribute in nodes with depth <= 5:
	2177 : used_pin_number [NUMERICAL]
	2007 : distance_from_last_transaction [NUMERICAL]
	1415 : distance_from_home [NUMERICAL]
	1344 : used_chip [NUMERICAL]
	1051 : online_order [NUMERICAL]
	883 : ratio_to_median_purchase_price [NUMERICAL]
	333 : repeat_retailer [NUMERICAL]

Condition type in nodes:
	10533 : HigherCondition
Condition type in nodes with depth <= 0:
	300 : HigherCondition
Condition type in nodes with depth <= 1:
	900 : HigherCondition
Condition type in nodes with depth <= 2:
	2099 : HigherCondition
Condition type in nodes with depth <= 3:
	4085 : HigherCondition
Condition type in nodes with depth <= 5:
	9210 : HigherCondition
Node format: NOT_SET

Training OOB:
	trees: 1, Out-of-bag evaluation: accuracy:0.999959 logloss:0.00147243
	trees: 11, Out-of-bag evaluation: accuracy:0.999974 logloss:0.000449287
	trees: 21, Out-of-bag evaluation: accuracy:0.999979 logloss:0.000224315
	trees: 31, Out-of-bag evaluation: accuracy:0.99998 logloss:0.000136587
	trees: 41, Out-of-bag evaluation: accuracy:0.999981 logloss:9.20093e-05
	trees: 51, Out-of-bag evaluation: accuracy:0.999981 logloss:8.97593e-05
	trees: 61, Out-of-bag evaluation: accuracy:0.999981 logloss:8.94364e-05
	trees: 71, Out-of-bag evaluation: accuracy:0.999982 logloss:8.88501e-05
	trees: 81, Out-of-bag evaluation: accuracy:0.999984 logloss:8.84244e-05
	trees: 91, Out-of-bag evaluation: accuracy:0.999982 logloss:8.83711e-05
	trees: 101, Out-of-bag evaluation: accuracy:0.999984 logloss:8.81076e-05
	trees: 111, Out-of-bag evaluation: accuracy:0.999984 logloss:8.72583e-05
	trees: 121, Out-of-bag evaluation: accuracy:0.999984 logloss:4.77278e-05
	trees: 131, Out-of-bag evaluation: accuracy:0.999986 logloss:4.78673e-05
	trees: 141, Out-of-bag evaluation: accuracy:0.999985 logloss:4.82169e-05
	trees: 151, Out-of-bag evaluation: accuracy:0.999985 logloss:4.75932e-05
	trees: 161, Out-of-bag evaluation: accuracy:0.999986 logloss:4.73845e-05
	trees: 171, Out-of-bag evaluation: accuracy:0.999986 logloss:4.72551e-05
	trees: 181, Out-of-bag evaluation: accuracy:0.999987 logloss:4.68039e-05
	trees: 191, Out-of-bag evaluation: accuracy:0.999987 logloss:4.72948e-05
	trees: 201, Out-of-bag evaluation: accuracy:0.999987 logloss:4.76341e-05
	trees: 211, Out-of-bag evaluation: accuracy:0.999987 logloss:4.82046e-05
	trees: 221, Out-of-bag evaluation: accuracy:0.999987 logloss:4.85401e-05
	trees: 231, Out-of-bag evaluation: accuracy:0.999987 logloss:4.89669e-05
	trees: 241, Out-of-bag evaluation: accuracy:0.999987 logloss:4.87233e-05
	trees: 251, Out-of-bag evaluation: accuracy:0.999987 logloss:4.92245e-05
	trees: 261, Out-of-bag evaluation: accuracy:0.999987 logloss:4.9563e-05
	trees: 271, Out-of-bag evaluation: accuracy:0.999987 logloss:4.95146e-05
	trees: 281, Out-of-bag evaluation: accuracy:0.999987 logloss:4.92848e-05
	trees: 291, Out-of-bag evaluation: accuracy:0.999986 logloss:4.97061e-05
	trees: 300, Out-of-bag evaluation: accuracy:0.999986 logloss:4.97547e-05

In [20]:
model.make_inspector().evaluation()

Evaluation(num_examples=800000, accuracy=0.99998625, loss=4.9754733907757326e-05, rmse=None, ndcg=None, aucs=None, auuc=None, qini=None)

In [22]:
app_ds = tfdf.keras.pd_dataframe_to_tf_dataset(app_test,label=label)

eval = model.evaluate(app_ds,return_dict =True)

for name, value in eval.items():
    print(f'{name}: {value:.4f}')

1/1 [==============================] - 0s 103ms/step - loss: 0.0000e+00 - accuracy: 1.0000
loss: 0.0000
accuracy: 1.0000

In [23]:
model.predict(app_ds,verbose =0)

array([[0.        ],
       [0.99999917],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.99999917],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]], dtype=float32)